runtime: nodejs20  # or whichever version is appropriate
env: standard
instance_class: F1  # Choose an appropriate instance class

automatic_scaling:
  max_instances: 1  # Set the maximum number of instances

env_variables:
  NODE_ENV: 'production'
